### ISSUE TITLE
Numbers omitted when formatted as shell or dotenv

### ISSUE THREAD

**Issue by cnunciato** [pulumi/esc#118]
Given the following environment file:

```yaml
values:
  one: 1
  two: 2
  pi: 3.14

  environmentVariables:
    ONE: ${one}
    TWO: "${two}"
    THREE: 3
    FOUR: "4"
    PI: ${pi}
```

`esc env open` produces the JSON I'd expect:

```
$ esc env open integer-test
{
  "environmentVariables": {
    "FOUR": "4",
    "ONE": 1,
    "PI": 3.14,
    "THREE": 3,
    "TWO": 2
  },
  "one": 1,
  "pi": 3.14,
  "two": 2
}
```

But when formatted as `shell` or `dotenv`, the values I'd expressed as numbers are missing:  

```
$ esc env open integer-test --format shell
export FOUR="4"
```

I'd expect to see all five environment variables exported, since all are derived from valid YAML:

```
$ esc env open integer-test --format shell
export ONE="1"
export TWO="2"
export THREE="3"
export FOUR="4"
export PI="3.14"
```

**Comment by pgavlin** [comment]
So this is intentional and probably undocumented, and I'm very open to changing the behavior here.

We decided to export only variables of type string in `shell`/`dotenv` format b/c they have a clear + predictable string representation (i.e. the identity function). We could extend this to all scalars (booleans + numbers) without too much surprise, I expect.

I'm less certain about what to do for arrays and objects, as these generally don't have a uniform representation when it comes to envvars (e.g. some systems may want an object to be JSON-serialized when represented as an envvar, some may want some key/value pair repo, etc.).

wdyt about exporting all scalars as their string representation? That would give us the behavior you expect.

And in the meantime you can work around the limitation by explicitly stringifying non-strings:

```yaml
values:
  one: 1
  two: 2
  pi: 3.14

  environmentVariables:
    ONE: {fn::toString: "${one}"}
    TWO: {fn::toString: "${two}"}
    THREE: {fn::toString: 3}
    FOUR: "4"
    PI: {fn::toString: "${pi}"}
```
