### ISSUE TITLE
Config retrieval should convert to relevent data structure automatically

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/esc#136]
Not sure where exactly this should go (I think it should likely go into the pulumi/pulumi) but filing it here for now, please feel free to move

I load an environment:

```yaml
# Pulumi.development.yaml
environment:
  - development
config:
  aws:region: us-west-2
```

I then load than config into my Pulumi program:

```python
"""An AWS Python Pulumi program"""
import pulumi


config = pulumi.Config()

aws = config.get("aws")
pulumi_environment_config = config.get("pulumi")

print(pulumi_environment_config)
print(type(pulumi_environment_config))
```

This returns the relevant config:

```
Diagnostics:
  pulumi:pulumi:Stack (esc-test-development):
    {"orgName":"lbrlabs"}
    <class 'str'>
```

But I was surprising to see that it's just a string. I have to `json.loads` it to make it useful:

```python
"""An AWS Python Pulumi program"""
import pulumi
import json


config = pulumi.Config()

aws = config.get("aws")
pulumi_environment_config = json.loads(config.get("pulumi"))

print(pulumi_environment_config)
print(type(pulumi_environment_config))
```

```
Diagnostics:
  pulumi:pulumi:Stack (esc-test-development):
    {'orgName': 'lbrlabs'}
    <class 'dict'>
```

Not exactly a showstopper, but I think it would be better if we can somehow make this step not required.

**Comment by cleverguy25** [comment]
@jaxxstorm Can you show how your environment is defined in this case?

**Comment by jaxxstorm** [comment]
@cleverguy25 do you want the environment definition, or maybe a screenshot?

**Comment by cleverguy25** [comment]
I think either would work

**Comment by jaxxstorm** [comment]
```
# values is a required top-level key
values:
  pulumi:
    orgName: lbrlabs
  aws:
    orgid: foo
  github:
    orgName: lbrlabs 
  environmentVariables:
    AWS_ORG_ID: ${aws.orgid}
  pulumiConfig:
    aws:
      orgid: ${aws.orgid}
    pulumi:
      orgName: ${pulumi.orgName}
    github:
      orgName: ${github.orgName}
```
