### ISSUE TITLE
Allow using variables within the values block

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/esc#148]
I want to do something like this:

```
imports:
  - root
# values is a required top-level key
values:
  aws:
    accountId: "00000"
    oidc:
      githubRoleArn: arn:aws:iam::${accountId}:role/github-actions-49e7448
      pulumiDeploymentsRoleArn: arn:aws:iam::${accountId}:role/pulumi-deploy-ff54f5f
  environmentVariables:
    AWS_GITHUB_ROLE_ARN: ${aws.oidc.githubRoleArn}
```

But it seems I can't leverage variables inside the values block. That'd be super nice!
