### ISSUE TITLE
Running `pulumi up` sends an incorrect subject identifier to Azure

### ISSUE THREAD

**Issue by toriancrane** [pulumi/esc#173]
### What happened?

Related to [this issue](https://github.com/pulumi/pulumi-azure-native/issues/2868).

After configuring Pulumi ESC to work with Azure and Pulumi IaC, I tried to run the `pulumi up` command to have my Azure resources deployed and ran into the following error:

```bash
  azure-native:resources:ResourceGroup (resource_group):
    error: autorest/Client#Do: Preparing request failed: StatusCode=0 -- Original Error: clientCredentialsToken: received HTTP status 401 with response: {"error":"invalid_client","error_description":"AADSTS700213: No matching federated identity record found for presented assertion subject 'pulumi:environments:org:pulumi:env:<yaml>'. Please check your federated identity credential Subject, Audience and Issuer against the presented assertion. https://docs.microsoft.com/en-us/azure/active-directory/develop/workload-identity-federation Trace ID: 20f6c59a-9821-47da-afb7-aafa724e6b01 Correlation ID: 1b19f0d7-cba3-4b0a-ae44-7489adf2454b Timestamp: 2023-11-07 09:11:45Z","error_codes":[700213],"timestamp":"2023-11-07 09:11:45Z","trace_id":"20f6c59a-9821-47da-afb7-aafa724e6b01","correlation_id":"1b19f0d7-cba3-4b0a-ae44-7489adf2454b"}
```

Somewhere in this OIDC workflow, `pulumi:environments:org:pulumi:env:<yaml>` is being sent as the subject identifier rather than the one that includes the name of my ESC environment.

### Example

1. [Configure Azure OIDC with Pulumi ESC](https://www.pulumi.com/docs/pulumi-cloud/oidc/azure/).
2. Add the following definition to the environment file:
```yaml
values:
  azure:
    login:
      fn::open::azure-login:
        clientId: your-client-id
        tenantId: you-tenant-id
        subscriptionId: your-subscription-id # without the `/subscriptions/` prefix
        oidc: true
  environmentVariables:
    ARM_USE_OIDC: 'true'
    ARM_CLIENT_ID: ${azure.login.clientId}
    ARM_TENANT_ID: ${azure.login.tenantId}
    ARM_OIDC_REQUEST_TOKEN: ${azure.login.oidc.token}
    ARM_OIDC_TOKEN: ${azure.login.oidc.token}
    ARM_SUBSCRIPTION_ID: ${azure.login.subscriptionId}
    ARM_OIDC_REQUEST_URL: https://api.pulumi.com/oidc

````
3. Create a new Pulumi Python project (`pulumi new azure-python`)
4. Update the stack settings file to import ESC environment file:

```yaml
environment:
  - your-environment-name
```

5. Run `pulumi up -y`

### Output of `pulumi about`

```bash
CLI          
Version      3.92.0
Go Version   go1.21.3
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  2.15.0
python        unknown

Host     
OS       amazon
Version  2
Arch     x86_64

This project is written in python: executable='/home/ec2-user/.pyenv/shims/python3' version='3.8.12'

Current Stack: pulumi/az-pulumi/dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/v-torian-pulumi-corp
User           v-torian-pulumi-corp
Organizations  v-torian-pulumi-corp, zephyr, pulumi
Token type     personal

Dependencies:
NAME                 VERSION
pip                  23.3.1
pulumi-azure-native  2.15.0
setuptools           68.2.2
wheel                0.41.3

Pulumi locates its logs in /tmp by default
```

### Additional context

When I add `pulumi:environments:org:pulumi:env:<yaml>` as the subject identifier to Azure, the workflow deploys successfully. 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
