### ISSUE TITLE
Fail to retrieve secrets from Google Secret Manager

### ISSUE THREAD

**Issue by simenandre** [pulumi/esc#177]
### What happened?

Attempting to access secrets from Google Secret Manager within GitHub Actions using a service account and workload identity provider. Expected to retrieve secrets successfully as when running `esc open <org>/<env>` locally, which shows the secrets without issue. The process involves the Google Secret Manager and GitHub Actions resources.

### Example

See this GitHub Action run: https://github.com/getbranches/conf/actions/runs/6797616773/job/18480096522

Here is the change:
https://github.com/getbranches/conf/commit/b9a20b6cb5df0d3a85028f283d73680d832c6f76

### Output of `pulumi about`

CLI
Version      3.92.0
Go Version   go1.21.3
Go Compiler  gc

Host
OS       darwin
Version  13.2.1
Arch     arm64

Backend
Name           pulumi.com
URL            https://app.pulumi.com/simenandre
User           simenandre
Organizations  bjerk, branches (and more)
Token type     personal

### Additional context

- The failure message received is: `Permission 'iam.serviceAccounts.getAccessToken' denied on resource (or it may not exist)`
- This issue is consistent across different executions and does not appear to be transient.
- All necessary permissions and roles have been verified for the service account.
- Works successfully on local CLI (with different accounts authenticated with application default auth).
- `esc` is v0.5.4

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by simenandre** [comment]
I removed the Google Secret Manager functionality for now in the repository I linked to, it isn't fixed. I just added the secret manually to the environment.

**Comment by simenandre** [comment]
Here is the environment that did not work:

```yaml
values:
  gcp:
    login:
      fn::open::gcp-login:
        project: 757907624116
        oidc:
          workloadPoolId: valid-workload-pool-id
          providerId: valid-provider-id
          serviceAccount: "one-account@my-secrets-project.iam.gserviceaccount.com"
    secrets:
      fn::open::gcp-secrets:
        login: ${gcp.login}
        access:
          api-token:
            name: api-token
  pulumiConfig:
    token: ${gcp.secrets.api-token}
```

(Some details are redacted)
