### ISSUE TITLE
Add diagnostics for omitted projections

### ISSUE THREAD

**Issue by lblackstone** [pulumi/esc#182]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Add diagnostics for cases where the user has set a projection (`pulumiConfig`, `environmentVariables`, `files`), but the projection is skipped due to an invalid value format.

A concrete example of this is setting a `files.KUBECONFIG` projection where the value is an object rather than a JSON string, as is the case for a `pulumi-eks` cluster's `kubeconfig` output.

This works:
```yaml
values:
  stacks:
    fn::open::pulumi-stacks:
      stacks:
        eks-cluster:
          stack: eks-yaml/demo
  pulumiConfig:
    kubernetes:kubeconfig: ${stacks.eks-cluster.kubeconfig}
  files:
    KUBECONFIG: {fn::toJSON: "${stacks.eks-cluster.kubeconfig}"}
```

This doesn't:
```yaml
values:
  stacks:
    fn::open::pulumi-stacks:
      stacks:
        eks-cluster:
          stack: eks-yaml/demo
  pulumiConfig:
    kubernetes:kubeconfig: ${stacks.eks-cluster.kubeconfig}
  files:
    # Notice the lack of toJSON
    KUBECONFIG: ${stacks.eks-cluster.kubeconfig}
```

In the non-working case, the `KUBECONFIG` projection fails silently.
