### ISSUE TITLE
Expose file paths as environment variable

### ISSUE THREAD

**Issue by jtmarmon** [pulumi/esc#196]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
In production our secrets are mounted to disk using K8s volumes. We then have an app `config.yaml` that references those secrets' filepath.  

In development, we want to use the `files` key to replicate this setup. We can create the secrets and `config.yaml` file this way, but (AFAICT) there's no way for the `config.yaml` key to reference the created file path for the secrets. It would be great if I could somehow write the filepath of one file into another.

This could work either by exposing to me the generated filepath, e.g. 
```yaml
files:
  MY_SECRET: hunter2
  MY_CONFIG: |
     secret_filepath: ${files.MY_SECRET.filepath}`
```

 or allowing me to specify the path instead of it being random, e.g.
```yaml
files:
  MY_SECRET: 
    value: hunter2
    path: /etc/secrets/my_secret
  MY_CONFIG: |
     secret_filepath: /etc/secrets/my_secret
```
