### ISSUE TITLE
Improve error message "receiver must be an array or an object"

### ISSUE THREAD

**Issue by jkodroff** [pulumi/esc#197]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Given this (invalid) environment:

```yaml

values: # This is a reserved key.
  aws: # This is an arbitrary key, not reserved.
    creds: # Arbitrary key
      fn::open::aws-login: # https://www.pulumi.com/docs/pulumi-cloud/esc/providers/aws-login/
        oidc:
          duration: 1h
          roleArn: arn:aws:iam::886783038127:role/esc-role-cf0356a
          sessionName: "my-esc-session"
  environmentVariables:
    AWS_ACCESS_KEY_ID: ${aws.creds.oidc.accessKeyId} # This guy and its friends are wrong. "oidc" segment should be removed
    AWS_SECRET_ACCESS_KEY: ${aws.creds.oidc.secretAccessKey}
    AWS_SESSION_TOKEN: ${aws.creds.oidc.sessionToken}
```

I get the following not-especially-helpful error message:

```text
$ esc env edit jkodrofftest/my-demo-environment
Error: updating environment definition: [0] 
Diags: receiver must be an array or an object
receiver must be an array or an object
receiver must be an array or an object
```

Could we reformat this to something like:

```text
unable to process "values.environmentVariables.AWS_ACCESS_KEY_ID". Referenced value "${aws.creds.oidc.accessKeyId}" not found.
# etc 
```
