### ISSUE TITLE
Support for non-importable values

### ISSUE THREAD

**Issue by jtmarmon** [pulumi/esc#200]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
I'd like to be able to have a key in the `value` section which when imported to other environments doesn't propagate. 

Example:

Imagine you have one env whose job is to read a secret from a secrets manager, so that multiple downstream envs can reuse that logic. .e.g

```yaml
# env-creds
values:
  _login:
    fn::open::aws-login:
      oidc:
        roleArn: arn:aws:iam::<>:role/Role
        sessionName: pulumi-environments-session
        duration: 1h
  _secrets:
    fn::open::aws-secrets:
      region: us-east-1
      login: ${_login}
      get:
        creds:
          secretId: myCredId
  _parsedCreds:
    fn::fromJSON: ${_secrets.creds}
  clientId: ${_parsedCreds.client_id}
  secret: ${_parsedCreds.client_secret}
```

When you import this into a downstream env, you're really doing it just to get the `clientId` and `secret` values, but the downstream env gets `_login`, `secrets`, `_parsedCreds`, etc which all get hard to read.

It's be nice if there was a way to prevent that from happening, either by denylisting them (e.g. an underscore prefix prevents propagation on import), or allowlisting the intended "exports"
