### ISSUE TITLE
ESC: multiple environments in stack config don't work 

### ISSUE THREAD

**Issue by ThorKarlsson** [pulumi/esc#212]
### What happened?

I was trying to break up my config into several ESC environments and then import them individually into my Stack config. When more than one environment was set, previous configurations became undefined. This seems to be because one of my environments contained an import. If none of the environments have an import the configuration works as expected but as soon as there is an import then only the environment with the import loads and the others are undefined.

```yaml
# Pulumi.dev.yaml
environment:
  - api-auth-dev
  - api-billing-dev
  - api-documents-dev
config:
  aws:profile: dev
  aws:region: ap-southeast-2
  ...
```

### Example

Environments:
```yaml
# env-a
values:
  pulumiConfig:
    foo: env-a-config
```

```yaml
# env-b
values:
  pulumiConfig:
    bar: env-b-config
```

```yaml
# Pulumi.dev.yaml
environment:
  - env-a
  - env-b
config:
 ...
```

```typescript
// index.ts

const config = new pulumi.Config();

console.log(`config.get("foo"): ${config.get("foo")}`)
console.log(`config.get("bar"): ${config.get("bar")}`)
```
```
Output:
  pulumi:pulumi:Stack (myhr-fullenv-dev):
    config.get("foo"): env-a-config
    config.get("bar"): env-b-config
```

This works as expected - but now if I import something in env-b, env-a will become undefined.

```yaml
# env-b
imports:
  - env-c-secrets
values:
  pulumiConfig:
    bar: env-b-config
```

```yaml
# env-c-secrets
values:
  password: 12345
```

Run the code again this is my output:
```
  pulumi:pulumi:Stack (myhr-fullenv-dev):
    config.get("foo"): undefined
    config.get("bar"): env-b-config
```

### Output of `pulumi about`

```
pulumi about

CLI
Version      3.96.2
Go Version   go1.21.4
Go Compiler  gc

Plugins
NAME     VERSION
aws      6.13.0
command  0.9.2
nodejs   unknown

Host
OS       darwin
Version  14.1
Arch     x86_64

This project is written in nodejs: executable='/Users/thor/.nvm/versions/node/v20.10.0/bin/node' version='v20.10.0'

Current Stack: myhr/myhr-fullenv/dev
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
