### ISSUE TITLE
Config editor inlines & escapes multiline strings with two newlines

### ISSUE THREAD

**Issue by jtmarmon** [pulumi/esc#217]
### What happened?

We have an ESC config with a YAML string in it. Typically the ESC editor preserves our formatting on save, but if we accidentally add an empty newline and save, pulumi collapses it into a single line. Would be great if the editor was a little more lenient on whitespace

### Example

- Create an ESC file with the following config and save
```yaml
values:
  myConfig: |-
    a: 1
      a2: 2
    b: 2
    c: 3
```
- Add a newline between any keys
- Observe the string has collapsed into a oneline string like
```yaml
values:
  myConfig: "a: 1\n  a2: 2 \n\nb: 2\nc: 3"
```

### Output of `pulumi about`

n/a

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by pgavlin** [comment]
Which editor are you using? Guessing that this is via any editor--the web UI or `esc env edit`--and is probably related to the pipeline we use to encrypt/decrypt secrets.

**Comment by pgavlin** [comment]
I can't repro this using `esc env init`/`esc env edit`.

- I created an empty environment using `esc env init`
- I edited the environment using `esc env edit` s.t. its definition was

```
values:
  myConfig: |-
    a: 1
      a2: 2
    b: 2
    c: 3
```

- I edited the environment again using `esc env edit` s.t. its definition was

```
values:
  myConfig: |-
    a: 1
      a2: 2
    b: 2

    c: 3
```

All formatting was preserved. Are there other entities in the environments where you're seeing the reformat?
