### ISSUE TITLE
Specify pulumi access token per command run

### ISSUE THREAD

**Issue by kennethlynne** [pulumi/esc#223]
### What happened?

I want to make use of a secret GITHUB_TOKEN from esc in a workflow like this:
```
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests

    steps:
      - name: Setup repository
        uses: actions/checkout@v3

      - name: Setup monorepo
        uses: ./.github/actions/setup-monorepo

     - uses: pulumi/actions@v5 # install pulumi

      - name: Get secrets
        run: pulumi env open org/github-actions --format dotenv >> $GITHUB_ENV
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Semantic release
        run: pnpm exec semantic-release

```
however it does not seem like pulumi picks this secret up correctly. Is it only possible to do it during set-up? 
![image](https://github.com/pulumi/actions/assets/390817/f2bca351-17fa-4c92-b257-2f8a18fa6de7)

This issue is either a request for documentation, a bug or a feature request, but I'm not sure.  

The quick and dirty workaround is this, add this before using secrets:
```
      - name: Make sure pulumi is authenticated
        run: pulumi login && pulumi whoami
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
```

### Example

Example provided above

### Output of `pulumi about`

Version      3.103.1
Go Version   go1.21.5
Go Compiler  gc

Host     
OS       darwin
Version  14.1.2
Arch     arm64

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
