### ISSUE TITLE
ESC AWS OIDC provider does not support Gov Cloud

### ISSUE THREAD

**Issue by MitchellGerdisch** [pulumi/esc#256]
### What happened?

Trying to use the AWS login provider to create OIDC temporary creds for AWS gov  cloud.
But get an error when doing an "open":
```
values.aws.login:
                                Error: WebIdentityErr: failed to retrieve credentials
caused by: InvalidIdentityToken: No OpenIDConnect provider found in your account for https://api.pulumi.com/oidc
                status code: 400, request id: xxxxxxxx
```

Also tested running on command line with `export AWS_ENDPOINT_URL_STS=sts.us-gov-west-1.amazonaws.com` and then `esc open` to see if ESC would consume the gov cloud endpoint. But it didn't.

### Example

```
values:
  aws:
    region: us-gov-west-1
    creds:
      fn::open::aws-login:
        oidc:
          duration: 1h
          roleArn: arn:aws:iam::xxxxxxxxxx:role/yyyyyyyyyyy
          sessionName: zzzzzzzzzz
  environmentVariables:
    AWS_ACCESS_KEY_ID: ${aws.creds.accessKeyId}
    AWS_SECRET_ACCESS_KEY: ${aws.creds.secretAccessKey}
    AWS_SESSION_TOKEN: ${aws.creds.sessionToken}
  pulumiConfig:
    aws:region: ${aws.region}
```

### Output of `pulumi about`

Happens in Pulumi Cloud UI as well as on command line with esc version 0.8.0

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
