### ISSUE TITLE
Add fn::concat support

### ISSUE THREAD

**Issue by kpitzen** [pulumi/esc#287]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I would like to have the ability to combine arrays in a given environment.  

One could imagine one environment, `test-0` with the following config:
```yaml
  pulumiConfig:
    examples-0:
      - foo
      - bar
```

and a second environment, `test-1` which imports `test-0` and would like to do the following:
```yaml
  pulumiConfig:
    examples-1:
      -baz
    examples:
      fn::concat:
        - ${pulumiConfig.examples-0}
        - ${pulumiConfig.examples-1}
```
Where the resulting config would be rendered as:
```yaml
  pulumiConfig:
    examples-1:
      -baz
    examples:
      - foo
      - bar
      - baz
```

### Affected area/feature

ESC
