### ISSUE TITLE
Environment variables not decrypting cyphertext

### ISSUE THREAD

**Issue by jtmarmon** [pulumi/esc#288]
### What happened?

I have an environment with secrets that are passed to `environmentVariables` like so:
```
values:
  aws:
    keyId: <my key>
    secretKey:
      fn::secret:
        ciphertext: <ciphertext>
  environmentVariables:
    AWS_ACCESS_KEY_ID: ${aws.keyId}
    AWS_SECRET_ACCESS_KEY: ${aws.secretKey}
  ```
when I run `esc run <env> -- env` the `AWS_SECRET_ACCESS_KEY` is set to literally "[secret]", not the unencrypted secret. This doesn't seem like an issue with decryption because when I run `esc open <env> --format=shell` the decrypted value is visible.

### Example

See above

### Output of `pulumi about`

ESC Version is `v0.8.3`. I originally ran into this issue on `0.7.0` and upgraded and nothing changed

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
