### ISSUE TITLE
Add a dotenv function to format configuration for environment files

### ISSUE THREAD

**Issue by lblackstone** [pulumi/esc#297]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
From @pgavlin:

> It'd be nice if there was a function like `fn::dotenv` that took an object and returned a dotenv-formatted string

We can write the following today:

```yaml
values:
  files:
    DOCKER_ENVFILE: |
      FOO=bar
```

This would be more flexible as structured configuration along these lines, which would generate an equivalent environment:

```yaml
values:
  dockerEnv:
    FOO: bar
  files:
    DOCKER_ENVFILE: { fn::dotenv: "${dockerEnv}" }
```
