### ISSUE TITLE
cli: document that `get`/`set` paths ~refer to physical YAML nodes, not logical esc nodes

### ISSUE THREAD

**Issue by pgavlin** [pulumi/esc#30]
e.g. consider this environment definition:

```yaml
values:
  aws:
    creds:
      fn::open::aws-login:
        oidc:
          roleArn: some-arn
          sessionName: name
  environmentVariables:
    AWS_ACCESS_KEY_ID: ${aws.creds.accessKeyId}
    AWS_SECRET_ACCESS_KEY: ${aws.creds.secretAccessKey}
    AWS_SESSION_TOKEN: ${aws.creds.sesstionToken}
```

The path `aws.creds["fn::open::aws-login"].oidc.roleArn` refers to the role ARN on line 6. A "logical" path might be `aws.creds.inputs.oidc.roleArn` or `aws.creds.inputs.roleArn`.
