### ISSUE TITLE
cli: support additional options for `files`

### ISSUE THREAD

**Issue by pgavlin** [pulumi/esc#301]
Some tools require that files have particular extensions in order to work properly (e.g. `tf -var-file=[path]` behaves differently if its argument's extension is `.json`). We could support situations like this by e.g. allowing the entry in `files` to be a `dict` that takes additional options:

```yaml
values:
  tfConfig:
    foo: bar
  files:
    TFVARS:
      pattern: tfvars-*.json
      content: { fn::toJSON: "${tfConfig}" }
```

We could also allow users to set permissions, etc.
