### ISSUE TITLE
Getting a secret from an imported environment returns `[unknown]`

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/esc#347]
### What happened?

When trying to retrieve a config value from one environment that was imported through another, the value returned was `[unknown]`

### Example

(Commands below are using the Pulumi CLI, but the one that returns the `[unknown]` value is the same with the ESC CLI.)

Follow steps:

1. Set up `demo-base` environment: `pulumi env init demo-base`
2. Set up `demo-dev` environment: `pulumi env init demo-dev`
3. Add the following to the `demo-dev` environment:

```
imports:
    - demo-base
```

4. Add secret to demo-base environment: `pulumi env set demo-base pulumiConfig.myBasePassword "my-base-password" --secret`
5. Add secret to demo-dev environment: `pulumi env set demo-dev pulumiConfig.myDevPassword "my-dev-password" --secret`
6. Get base secret from base environment: `pulumi env get demo-base pulumiConfig.myBasePassword --show-secrets --value json`
7. Get dev secret from dev environment: `pulumi env get demo-dev pulumiConfig.myDevPassword --show-secrets --value json`
8. Try to get base secret from dev environment: `pulumi env get demo-dev pulumiConfig.myBasePassword --show-secrets --value json`

(Will return `[unknown]`)

if you run `pulumi env open demo-dev` that works correctly and the following code works as expected:

```typescript
import * as pulumi from "@pulumi/pulumi";

const config = new pulumi.Config();

export const basePw = config.get("myBasePassword");
export const devPw = config.get("myDevPassword");
```

when `Pulumi.dev.yaml` is as follows:

```yaml
environment:
  - demo-dev
```

This is what my `demo-base` environment looks like:

```yaml
values:
  pulumiConfig:
    myBasePassword:
      fn::secret:
        ciphertext: ZXNjeAAAAAEAAAEA28KPa3Jj1chaQtbF+Hahccp22+0BMvymrx0ta5PzEX3/yKVZCwJ044qt4CSHhK6h

```

this is what my `demo-dev` environment looks like:

```yaml
imports:
  - demo-base
values:
  pulumiConfig:
    myDevPassword:
      fn::secret:
        ciphertext: ZXNjeAAAAAEAAAEAHuH2JF7Gz4ad/e3ZTfR63nN6AA2G+Llrktj2HDXAvfia57zbhR0XTaQqd+oetes=

```

(don't forget to delete the environments when you're done: `pulumi env rm demo-dev -y && pulumi env rm demo-base -y`)

### Output of `pulumi about`

```
CLI
Version      3.121.0
Go Version   go1.22.4
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  nodejs  unknown

Host
OS       darwin
Version  14.5
Arch     arm64

This project is written in nodejs: executable='/Users/piers/.nvm/versions/node/v20.11.1/bin/node' version='v20.11.1'

Current Stack: pierskarsenbarg/esc-secrets-issue/dev

TYPE                 URN
pulumi:pulumi:Stack  urn:pulumi:dev::esc-secrets-issue::pulumi:pulumi:Stack::esc-secrets-issue-dev


Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/pierskarsenbarg
User           pierskarsenbarg
Organizations  pierskarsenbarg, karsenbarg, team-ce, gitlab-test-piers, demo
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.121.0
@types/node     18.19.39
typescript      5.5.2

Pulumi locates its logs in /var/folders/x8/cdd9j87s607fwpy0q62mfmmw0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
