### ISSUE TITLE
1Password errors in Pulumi UI

### ISSUE THREAD

**Issue by PhilBroderickCrezco** [pulumi/esc#428]
### What happened?

Using the 1Password integration to retrieve secrets from a 1Password vault, everything works fine the first time round, during initial save. I can use the `Open` functionality from the environment UI in Pulumi Cloud to retrieve and decrypt the secret from 1Password.

However, if I edit the configuration (adding new secrets/updating existing) I get the following error:

```
environment-test:17:5 - values["1password"]:
	Error: error creating client
```

By re-entering the service account auth token (and marking as a secret) and saving again, I can retrieve the secrets once again. What I suspect is happening is that it's not decrypting the cipher of the token or something along those lines?

Might be something similar to https://github.com/pulumi/esc/issues/294. The service token is 100% correct, as I can use it locally with the 1Password CLI, and it works in the Pulumi environment until I make updates.

### Example

Example configuration:
```yaml
values:
  1password:
    fn::open::1password-secrets:
      get:
        api_credentials:
          ref: op://Engineering/api_user/credential
      login:
        serviceAccountToken:
          fn::secret:
            ciphertext: <ENCRYPTED_SERVICE_ACCOUNT_AUTH_TOKEN>
```

Steps to reproduce:
- Configure environment with 1Password integration (via table view), setting the token to secret and add a value secret path/ref
- Save and click "Open" in Pulumi Environment UI to retrieve the secret - confirm it works
- Update the secret to trigger a re-save (path change will do fine)
- Click "Open" once again and experience error.

### Output of `pulumi about`

N/A - this is all through Pulumi Cloud.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
