### ISSUE TITLE
Add comments to pulumi ESC configs

### ISSUE THREAD

**Issue by antspy** [pulumi/esc#475]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It would be nice if we could add comments to the pulumi esc configs & secrets. This helps with understanding why tokens are there, and allows for better code documentation.

**Comment by smithrobs** [comment]
hey @antspy I could be misunderstanding the ask here - comments [are supported today](https://www.pulumi.com/docs/esc/reference/) in an ESC environment via `#`:

```yaml
# values is a required top-level key
values:
  example: # this is an example
    setting: changeme
  example2:
    setting: ${example.setting}
```

If you mean comments on the ESC environments themselves in Pulumi Cloud, right now there are revision tags and environment tags which can be used as a comment mechanism.

If none of these fit your proposed use case, would you provide a quick code/config example of what you're thinking?
