### ISSUE TITLE
Pulumi config namespaces containing period are converted to YAML mapping by table view

### ISSUE THREAD

**Issue by gunzy83** [pulumi/esc#490]
### What happened?

I have not run into this myself as I use the YAML editor, but we have users in our org that infrequently have to update values that are source values that are mapped into the config keys in `pulumiConfig`. When they use the table view, on save our Pulumi configuration namespaces are converted to YAML mappings based on the location of periods. This is only a problem with table view and works in all other contexts, including the ESC CLI.

### Example

Trivial reproduction:
```yaml
values:
  my-app:
    db-password:
      fn::secret:
        ciphertext: some-ciphertext
  pulumiConfig:
    pendula.app.my-app:db-password: ${my-app.db-password}
```
Edit the `my-app.db-password` value and save, it will get turned into:
```yaml
values:
  my-app:
    db-password:
      fn::secret:
        ciphertext: some-new-ciphertext
  pulumiConfig:
    pendula:
      app:
        my-app:db-password: ${my-app.db-password}
```

### Output of `pulumi about`

Unrelated but here it is for one of our projects:

```
Found no pending operations associated with dev-apse2

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/gunzy83
User           gunzy83
Organizations  gunzy83, ZiplineCloud
Token type     personal

Dependencies:
NAME                              VERSION
@pulumi/kubernetes                4.21.1
@typescript-eslint/eslint-plugin  6.21.0
@ziplinecloud/stack               1.5.0
eslint                            8.57.1
prettier                          3.5.2
@pulumi/aws                       6.69.0
@pulumi/pulumi                    3.152.0
@pulumi/random                    4.17.0
@typescript-eslint/parser         6.21.0
@ziplinecloud/aws                 1.2.5
typescript                        5.7.3
@types/node                       20.17.19
@ziplinecloud/kubernetes          1.3.1
eslint-config-airbnb-base         15.0.0
eslint-config-prettier            9.1.0
eslint-plugin-prettier            5.2.3
eslint-plugin-import              2.31.0

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
