### ISSUE TITLE
Add support for tags

### ISSUE THREAD

**Issue by lblackstone** [pulumi/esc#5]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
It would be helpful to include first-class tag support as part of the ESC definition. I'm picturing something like a `tags` section that supports key/value pairs.

Example:
```yaml
imports:
  - foo
  - bar

tags:
  org: acme-corp
  environment: staging

values:
  object:
    array: [ "hello", "world" ]
```
