### ISSUE TITLE
Generic OIDC token provider

### ISSUE THREAD

**Issue by jkodroff** [pulumi/esc#547]
It would be helpful if we had a generic OIDC token provider, similar to [GitLab CI/CD's solution](https://docs.gitlab.com/ci/secrets/id_token_authentication/):

```yaml
job_with_id_tokens:
  id_tokens:
    FIRST_ID_TOKEN:
      aud: https://first.service.com/
    SECOND_ID_TOKEN:
      aud: https://second.service.com/
  script:
    - first-service-authentication-script.sh $FIRST_ID_TOKEN
    - second-service-authentication-script.sh $SECOND_ID_TOKEN
```

This would enable more orgs to use Pulumi ESC when there's no specialized provider.
