### ISSUE TITLE
Add a table-based UI for creating and editing environments

### ISSUE THREAD

**Issue by lukehoban** [pulumi/esc#62]
Today we have a document-based editor for environments inside Pulumi Cloud.

We would like to also offer a path-based editor using a more traditional table based UX.  This would allow a simple opoint-and-click interface for editing environments. 

The fundamental data model is still a document, but this editor can represent that document via a path-based UI. This leverages and surfaces similar model for path-based access to environments as with the `esc env get` and `esc env set` commands.

Here's a sketch of the expected user interface:
![IMG_8283](https://github.com/pulumi/esc/assets/223467/ed9185d5-5628-482b-9b2e-a5db789d74d4)

**Comment by stephen-cox-nzx** [comment]
Two issues:
 - You need at least one static key/value in the pulumiConfig section in an environment that inherits a pulimiConfig section, otherwise the pulumiConfig section is not present in the JSON
- the evaluation of an inherited pulimiConfig section does not consider "values:" key/values overridden in the current file. This means "templating with defaults" becomes a little bit more duplicated.

i.e.:
*common_env*
```yaml
# common_env
values:
  tagging:
    solution: "override at implementation"
pulumiConfig:
    tag_solution: ${tagging.solution}
```

*implemented_env*
```yaml
# implemented_env
imports:
   - common_env
values:
  tagging:
    solution: "Environment Override"
pulumiConfig:
   nonempty: "Something to ensure pulumiConfig exists and returns inherited values"
  # require a duplicate tag_solution: ${tagging.solution} to use redefined value
  # tag_solution: ${tagging.solution} 
```
in a perfect world, implemented_env json would automagically be like:
```json
{
"tagging": {
  "solution": "Environment Override"
},
"pulumiConfig": {
    "nonempty": "Something to ensure pulumiConfig exists and returns inherited values",
    "tag_solution": "Environment Override",
}
}

```
